### ISSUE TITLE
filter bug ：使用forbidden_urls来过滤domain、半角字符转全角字符

### ISSUE THREAD

**Issue by wwewwt** [XinrunDu/Chinese-Tiny-LLM#6]
1、
![image](https://github.com/Chinese-Tiny-LLM/Chinese-Tiny-LLM/assets/3361335/bdd078b6-d5f7-4f47-88d0-8c2ac67b13c6)
doamin 拼写错误，应该是 domain
forbidden_urls  是一个集合，in 方法是全匹配才回返回True  ，
但因为forbidden_urls 里面存的是url，而 doamin 是url的一个子集，所以domain 永远匹配不上，相当于这个domain的过滤条件失效了

2、
![image](https://github.com/Chinese-Tiny-LLM/Chinese-Tiny-LLM/assets/3361335/862e5aab-f0a9-4cb5-9fa0-56bfbd566540)
功能注释显示的是“半角字符转全角字符”，这个在MAP-CC的数据集中也可以确认，中文文本都是全角字符
但是这里的代码实现却是“全角字符转半角字符”

**综上，这个代码质量真的是一言难尽，这个真的是你们这个开源工作中使用的代码吗？其余的话不说了，看你们后续的开源表现吧，不要像某福报厂，为了开源而开源。**

**Comment by panDing19** [comment]
1. 对于第一个问题，我们采用前缀树来解决url search匹配的问题，已经修复。我们并没有用domain的文件来过滤，当然你可以选择用domain来过滤。
2. 第二个问题，是我们的comment写错了，实际是按照代码中的执行的，即全角转半角。数据集中存在全角字符，是因为我们只对zh-cc进行了过滤处理 。其余部分的数据并没有采用进行过滤处理，因此会存在全角符号。
